# Generated by Django 4.1.7 on 2023-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="title_tag",
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
