# Generated by Django 4.1.7 on 2023-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="url_post",
            field=models.URLField(null=True),
        ),
    ]
